services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - frontend
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: always
      placement:
        constraints:
          - "node.role==manager"
  webui:
    image: 127.0.0.1:5000/webui
    build: ./webui
    ports:
      - "5100:5100"
    networks:
      - frontend
    depends_on:
      - rabbit
    deploy:
      replicas: 1
      restart_policy:
        condition: always
      placement:
        constraints:
          - "node.role==manager"
  webcrawler:
    image: 127.0.0.1:5000/webcrawler
    build: ./webcrawler
    networks:
      - frontend
    depends_on:
      - rabbit
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==manager"
  taskscheduler:
    image: 127.0.0.1:5000/taskscheduler
    build: ./taskscheduler
    networks:
      - backend
    depends_on:
      - rabbit
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==manager"

networks:
  frontend:
  backend:
