services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - frontend
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==manager"
  pulsar:
    hostname: pulsar
    image: apachepulsar/pulsar:3.2.1
    ports:
      - "8080:8080"
      - "6650:6650"
    networks:
      - frontend
      - backend
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
    command: bin/pulsar standalone
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==manager"
  webui:
    image: 127.0.0.1:5000/webui
    build: ./webui
    ports:
      - "5100:5100"
    networks:
      - frontend
    depends_on:
      - rabbit
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==manager"
  webcrawler:
    image: 127.0.0.1:5000/webcrawler
    build: ./webcrawler
    networks:
      - frontend
    depends_on:
      - rabbit
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==manager"
  worker:
    image: 127.0.0.1:5000/worker
    build: ./worker
    networks:
      - backend
    depends_on:
      - rabbit
    deploy:
      replicas: 15

networks:
  frontend:
  backend:

volumes:
  pulsardata:
  pulsarconf:
