services:
  pulsar:
    hostname: pulsar
    image: apachepulsar/pulsar:3.2.1
    ports:
      - "8080:8080"
      - "6650:6650"
    networks:
      - frontend
      - backend
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
    command: bin/pulsar standalone
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==manager"

  webcrawler:
    image: 127.0.0.1:5000/webcrawler
    build: ./webcrawler
    networks:
      - frontend
    depends_on:
      - pulsar
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"

  worker:
    image: 127.0.0.1:5000/worker
    build: ./worker
    networks:
      - backend
    depends_on:
      - pulsar
    deploy:
      replicas: 1

networks:
  frontend:
  backend:

volumes:
  pulsardata:
  pulsarconf:
