# A single configration file to rule them all

github_access_token:

instances:
  name_prefix: UZ                 # Used to create the node name
                                  # Template: prefix-int(4)-headnode
                                  # Template: prefix-int(4)-worker-n
  headnode:
    instance_flavor: ssc.xlarge.highcpu
    instance_source: Ubuntu 22.04 - 2024.01.15
    authorized_keys: USAMA-ACCESS-KEY
    private_network: UPPMAX 2024/1-4 Internal IPv4 Network
    security_groups:
      - default
      - usama-sg
    floating_ip_pool: null
    floating_ip_addr: null
    instance_configs: configs/headnode-cfg.yaml
  workernodes:
    numworkers: 2
    workercfgs:
      instance_flavor: ssc.xlarge
      instance_source: Ubuntu 22.04 - 2024.01.15
      authorized_keys: USAMA-ACCESS-KEY
      private_network: UPPMAX 2024/1-4 Internal IPv4 Network
      security_groups:
        - default
      floating_ip_pool: null
      floating_ip_addr: null
      instance_configs: configs/worknode-cfg.yaml
