#cloud-config

apt_update: true
apt_upgrade: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC14CaNz7BAK1sDWZGAMvHu1NEonqltKL7X2kVNvAyZnxyksvN3WYSJqt1PVzlsT/wBqONeCwGgDEjIVTViaiZV4Tp7lE/5rotKIfEv13cj1Gj74VYJi21I9q7saOwVVodqmanvQU07zQKo4KsNBrXH9flyIqplHUGy11yN56KQHNyJmKVREN7OTA+A6FEtVyVgdQVSkp3NWobXRyHt/QV5NJ+tTDC/75VqOZQPeSkGetnInmDA3Uo0ZuxMuUymYVfa8EW2QPKLp90DKhsRubIkDSIPPdinjoRUSqbXjj2AGMKntrwdbk5HGcFoUsHlzeW+q/BZ+dfIVDX7DL1S8poWLGJKiJ5HSufLyD5WkguThDSUqzxEtOHBDK1YxgjxvvXFscF0gyVVzJq2ikS5xLK/PUTzwA3PPPxLwhOvS2nhJq5Lw8zATWqkRTrhQK0BX70gO/jAfmDW06J0i+B1Sb+nLg2OCkz3ItvOwGhdx9v1svaR+R11LQFAzZ/uIscpu3U= user\usaza315@IT-5GGC5W3

packages:
  - python3-pip
  - python3-dev
  - build-essential
  - tmux
  - apt-transport-https 
  - ca-certificates 
  - curl 
  - software-properties-common

byobu_default: system

runcmd:
  - printf "..."
  - printf "\n=========================================================================================================\n"
  - printf "\n=========================================================================================================\n"
  - printf "\n=========================================================================================================\n"
  - printf "\n\nAdding docker repository ...\n"
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update -y

  - printf "..."
  - printf "\n=========================================================================================================\n"
  - printf "\n=========================================================================================================\n"
  - printf "\n=========================================================================================================\n"
  - printf "\n\nInstalling dependencies ...\n"
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  
  - printf "..."
  - printf "\n=========================================================================================================\n"
  - printf "\n=========================================================================================================\n"
  - printf "\n=========================================================================================================\n"
  - printf "\n\nInitializing docker swarm ...\n"
  - docker swarm init > /dev/null

  - printf "..."
  - printf "\n=========================================================================================================\n"
  - printf "\n=========================================================================================================\n"
  - printf "\n=========================================================================================================\n"
  - printf "\n\nObtain swarm token ...\n"
  - docker swarm join-token worker -q > /swarm-token.txt

  - printf "..."
  - printf "\n=========================================================================================================\n"
  - printf "\n=========================================================================================================\n"
  - printf "\n=========================================================================================================\n"
  - printf "\n\nStarting a local registry ...\n"  
  - docker service create --name registry --publish published=5000,target=5000 registry:2

  - printf "..."
  - printf "\n=========================================================================================================\n"
  - printf "\n=========================================================================================================\n"
  - printf "\n=========================================================================================================\n"
  - printf "\n\nCloning core repository ...\n"
  - git clone https://github.com/UniversityCourseWork/UU-DEII-Project.git /project

  - printf "..."
  - printf "\n=========================================================================================================\n"
  - printf "\n=========================================================================================================\n"
  - printf "\n=========================================================================================================\n"
  - printf "Installing dependencies for discovery ...\n"
  - pip3 install -r /project/unittester/discovery/requirements.txt

  - printf "..."
  - printf "\n=========================================================================================================\n"
  - printf "\n=========================================================================================================\n"
  - printf "\n=========================================================================================================\n"
  - printf "Start control application ...\n"
  - tmux new-session -d -s discoveryService
  - tmux send-keys -t discoveryService "python3 /project/unittester/discovery/discovery.py --host=0.0.0.0 --port=5200 --debug" C-m
  - tmux detach -s discoveryService

  - printf "..."
  - printf "\n=========================================================================================================\n"
  - printf "\n=========================================================================================================\n"
  - printf "\n=========================================================================================================\n"
  - printf "\n\nCopying common files to all services ...\n"
  - cp /project/unittester/rabbit-client/* /project/unittester/worker/ 
  - cp /project/unittester/rabbit-client/producer.py /project/unittester/webcrawler/ 

  - printf "..."
  - printf "\n=========================================================================================================\n"
  - printf "\n=========================================================================================================\n"
  - printf "\n=========================================================================================================\n"
  - printf "Pushing images to registery ...\n"
  - docker compose -f /project/unittester/composev2.yaml pull
  - docker compose -f /project/unittester/composev2.yaml build
  - docker compose -f /project/unittester/composev2.yaml push

  - printf "..."
  - printf "\n=========================================================================================================\n"
  - printf "\n=========================================================================================================\n"
  - printf "\n=========================================================================================================\n"
  - printf "\n\nDeploy the application stack on swarm ...\n"
  - docker stack deploy --compose-file /project/unittester/composev2.yaml unittester
